# ----------------------------------- Basic ---------------------------------- #

title: INTIA
email: intia@th-koeln.de
description: >- # this means to ignore newlines until "baseurl:"
  A plattform for methods, techniques, toolkits and patterns for participative development in a social context.
baseurl: ""
url: ""
markdown: CommonMarkGhPages
# ----------------------------------- Theme ---------------------------------- #

theme: intia-theme
footer_menu: footer

# ---------------------------------- Plugins --------------------------------- #
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sass-converter
  - jekyll-titles-from-headings
  - jekyll-watch
  - jekyll-hyperlinkify-glossary
  - jekyll-target-blank
github: [metadata]
sass:
  style: compressed
# ------------------------- Defaults and Collections ------------------------- #

# Defaults
defaults:
  - scope:
      type: pages
      path: pages
    values:
      layout: default
  - scope:
      type: posts
      path: _posts
    values:
      permalink: /blog/:title/
      path: [Blog, Neuigkeiten]
      layout: default
  - scope:
      type: articles
      path: _articles
    values:
      permalink: /articles/:title/
      path: [Blog, Fachartikel]
      layout: default
  - scope:
      type: glossary
      path: _glossary
    values:
      permalink: /wissen/woerterbuch/:title/
      breadcrumbs: [Wissen, Wörterbuch]
      layout: default  
  - scope:
      type: building_blocks
      path: _building_blocks
    values:
      permalink: /werkzeuge/bausteine/:title/
      breadcrumbs: [Werkzeuge, Bausteine]
      layout: default   
  - scope:
      type: prototypes
      path: _prototypes
    values:
      permalink: /werkzeuge/prototypen/:title/
      breadcrumbs: [Werkzeuge, Prototypen]
      layout: default   
  - scope:
      type: methods
      path: _methods
    values:
      permalink: /werkzeuge/methoden/:title/
      breadcrumbs: [Werkzeuge, Methoden]
      layout: default   

# Collections
collections_dir: collections
collections:
  glossary:
    output: true
  methods:
    output: true
  articles:
    output: true
  building_blocks:
    output: true
  prototypes:
    output: true

# --------------------------- Includes and Excludes -------------------------- #

# Include
include:
  - CNAME

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
