radar:
  id: 'radar'
  name: 'Methodenradar'
  showName: true
  showAllSectorsText: 'Alle Quadranten'
  legendDropdownText: 'Legende'
  defaultColor: '#7db6b0'
  renderResolution: 518
  linkPrefix: '/werkzeuge/methoden/'
  linkSuffix: ''

sector:
  showName: true
  nameOffset: 5

segment: 
  colorGradient: true
  colorGradientLimit: 1.65
  showName: false
  showNameAsId: true
  padding: 4

blip:
  size: 1
  defaultColor: '#1e7d73'
  margin: 10
  outerCircleRadius: 0