name: Update production

on:
  push:
    branches:
      - main

env:
  URL: test.intia.de

jobs:
  build-test:
    runs-on: ubuntu-20.04
    environment:
      name: production
      url: https://${{ env.URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0
        with:
          ref: "gh-pages"

      - name: Checkout Prod Target
        uses: actions/checkout@v2.4.0
        with:
          repository: th-koeln-intia/intia-prod
          path: "destination"
          token: ${{ secrets.PAT }}
      - name: Push to production
        run: |
          rm -r ./destination/*
          rsync -Rr --exclude=.git --exclude=destination . destination
          cd destination
          echo ${{ env.URL }} > CNAME
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com     
          git add .
          git commit -m $GITHUB_SHA
          git push
